### PR TITLE
Numerous issues and code re-factoring.

### PR DESCRIPTION
**Pull request by kabalin**
This pull request contains block_panopto code re-factoring to match Moodle [coding style](https://docs.moodle.org/dev/Coding_style) and fixes issues:
#26 - fixed in https://github.com/Panopto/Moodle-2.0-Plugin-for-Panopto/commit/5d837fc7e9ef5c0a5f4fbcea360e79869a3c9801
#34 - fixed in https://github.com/Panopto/Moodle-2.0-Plugin-for-Panopto/commit/cfe7292b53d0859b7fa91aa0ca58be239dfa0619
#35 - fixed in https://github.com/Panopto/Moodle-2.0-Plugin-for-Panopto/commit/010633250fe1a7dd6cd238b0f3f11c0b5077c5e7
#36 - fixed in https://github.com/Panopto/Moodle-2.0-Plugin-for-Panopto/commit/e24e7f0331d27a3ed4ec3bc3c0d14ae348a322b9
#37 - fixed in https://github.com/Panopto/Moodle-2.0-Plugin-for-Panopto/commit/0758965b9f104156c826233f0dca70136965209a

The pull request includes some significant changes that removes obsolete code instances and optimises existing to make future development work on plugin simplier and functionality more clear.

### CODE REVIEW

**Comment by kabalin** [comment]
It took nearly 6 hours to rebase all my commits on top of changes you merged last week, had to send pull request earlier ;)

I tired to describe each change in details in commit message. Just to keep revision process clear enough, if you have any questions or comments related to particular commit I suggest to discuss it within that particular commit (if you click on any commits listed above it will open the diff with comments box at the bottom). More general questions can be discussed here in the pull request itself.

**Comment by Panopto** [comment]
Thanks for all this hard work! We did a round of clean up to try to port your changes manually and that lead to the other change that you referenced.

I am tracking an internal work item to consider and test this pull request next week.

**Comment by kabalin** [comment]
One more commit is added that is fixing the provisioning link within the block editing screen of the block that has already been provisioned (see above).

**Comment by Panopto** [comment]
Hello Kabalin,

We attempted to review this pull request for inclusion in the main branch, but it has too many changes for us to properly manage.

Would you be willing to submit the changes one at a time so we can consider each one's merits individually? We would like to take your changes, but we cannot accept them all at once.

Jenn

**Comment by kabalin** [comment]
Jenn, thanks for reviewing the pull request. You could just manage them on one-by-one basis (review individually) and share your concerns once you spotted something that require clarification or changes. 

The main problem is that many of my changes depend on each other, so submitting them as individual patches means a lot of work to rebase each on latest master, and does not make sense in some cases (e.g. if one of them changes something that affects other patches).

What if you tell me up to which commit you can merge, and I will shorten the pull request down to that patch, and create another pull request with the rest of patches for further discussion?

**Comment by kabalin** [comment]
Hmm, just noticed you merged ActiveDev that introduced massive formatting change prior to any of my patches. OK, more work then to rebase my changes on top of master again...

**Comment by Hiroshi-p** [comment]
@kabalin 
I am sorry that this conversation becomes unattended for long time.
In general, we may not take big refactoring because of the risk of regression.
If you have any pull request that may fix specific problem(s), please submit pull requests for individual problem.
Also, we are working on to satisfy coding guideline separately.

**Comment by kabalin** [comment]
@Hiroshi-p no problem. The code diverted since March 2015, so most of the patches are either irrelevant or require significant refactoring I suppose. At the point of fulfilling pull request it could have been applied cleanly though, shame you did not allocate anyone to carry out revision and integration - this was a large chunk of work to bring Panopto to Moodle core standards, optimising performance and clean-up. Anyway, feel free to use any commits if you find anything is still relevant.

**Comment by Hiroshi-p** [comment]
@kabalin 
Thank you for your feedback.
Actually we are working on updating the code to follow Moodle standard and it is being tested now.
Also, we looked at each of your individual changes and we are going to take your fix for #26, #34, #35, #37. This is also being tested now.
Thanks again for your contribution.

**Pull request closed without merging**
