### PR TITLE
62_patch

### PR DESCRIPTION
**Pull request by Syxton**

### CODE REVIEW

**Comment by Hiroshi-p** [comment]
Did it work?
Looks like this change fires 'enrol_add' and 'enrol_remove' which do not match the event names in update_user.php.

**Comment by Syxton** [comment]
@Hiroshi-p Sorry about that.. fixed now

**Comment by Hiroshi-p** [comment]
Thanks. I think this is almost ready to merge. Just a little more help would be appreciated.
1. Did you test this on your side? Or, do you expect Panopto to test this?
2. Could you add a comment to this new method about what you explained in https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/pull/70, something like this event fires when enrolment is suspended and reactivated, but not newly enrolled or removed? It may be actually better idea to put your entire experimental result at the top of this file.

**Comment by Syxton** [comment]
@Hiroshi-p 

1.  I did test this locally, but only with debug messages that let me know if the expected methods were being fired off.  I think Panopto should test this in a live environment before merging.

2.  done.  Thanks

**Comment by Hiroshi-p** [comment]
@Syxton Thanks. I am going to keep this pull request open and I am going to merge it when we have a chance to test this.

**Comment by jmalmsten-panopto** [comment]
Applied this change, but couldn't do a direct merge since the branches varied too much by the time I pulled it in.

**Pull request closed without merging**
