### PR TITLE
2023083100 release code

### PR DESCRIPTION
**Pull request by zeroAps**
This is the current stable release version of the Panopto plug-in for Moodle. It is recommended that customers update to this version of the block.

This version supports (a) Moodle 3.9, 3.11, 4.0, 4.1, 4.2 running with PHP 7.4 and 8.0 and (b) Panopto version 10.6.1 or later.

Below is the list of updates from the previous beta release (2023031400).
- Added support for Moodle 4.2
- Fixed an issue with the Moodle Block plugin that could result in course assignment folders being returned when remapping a course.
- Fixed a silent failure when attempting to map a Moodle course to a Panopto folder that was already inheriting permissions. Users will now see an error message in this case.
- Fixed an issue when using the Panopto External Tool in Moodle 4.1 that could in some cases lead to a failure to view the session chooser when selecting content to embed from Panopto.
- Improved performance when loading LTI tools for Panopto.
- Fixed a number of PHP warnings that could appear if a Moodle site was set to show debugging messages.
- Fixed an issue that could result in thumbnails for videos added to a Moodle assignment using the Panopto Student Submission tool to fail to be visible in Moodle.
- Fixed an issue that could lead to calls from Moodle to the Panopto API to fail if the Moodle server was using a proxy.

### CODE REVIEW

**Review by kbaum-panopto — APPROVED** [review]

**Comment by jrchamp** [comment]
I saw that you fixed the PHP 8.1 issue (#197, #198), for example:
https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/blob/2ff5dc020adcec51b21f100d62da920084228814/lib/AuthManagement/AuthManagementWsdlClass.php#L643

Just so you know, the `mixed` return type is only available beginning in PHP 8.0 and the minimum Moodle version for PHP 8.0 is Moodle 3.11.8.

Right now, this plugin programmatically claims to support Moodle 2.7: https://github.com/Panopto/Moodle-2.0-plugin-for-Panopto/blob/2ff5dc020adcec51b21f100d62da920084228814/version.php#L34-L35

In case you don't already have the Moodle version strings: https://moodledev.io/general/releases

**Comment by sharpchi** [comment]
@jrchamp - really good spot, was about to update our site with this. Mixed return types are not valid in PHP 7.4. It will throw an exception.
Running this sample code
```
<?php

/**
 * Test me return values
 * @return mixed
 */
function testme(): mixed {
	return [1,2,3];
}

print_r(testme());
```
In PHP 7.4 returns
```
Fatal error: Uncaught TypeError: Return value of testme() must be an instance of mixed, array returned in /home/user/scripts/code.php:8
Stack trace:
#0 /home/user/scripts/code.php(11): testme()
#1 {main}
  thrown in /home/user/scripts/code.php on line 8
```
Unless the code requires a min PHP 8.0, the mixed return type should only be in the phpdoc block

**Comment by jrchamp** [comment]
To allow for backward compatibility while avoiding Deprecated warnings in PHP 8.1, you may need to use the [ReturnTypeWillChange attribute](https://php.watch/versions/8.1/ReturnTypeWillChange)

```php
    #[\ReturnTypeWillChange]
    public function current() {
```

That example was pulled directly from PHP's [Iterator examples](https://www.php.net/manual/en/class.iterator.php#iterator.examples)

**Comment by zeroAps** [comment]
Thank you for reporting this. We just made a new release which added attribute for backward compatibility.

**Pull request merged**
